# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{7d46aa4e-7486-4f77-ab47-81125f1a5723}',
        'interfaces': ['nsIZenBoostsBackend'],
        'contract_ids': ['@mozilla.org/zen/boosts-backend;1'],
        'type': 'zen::nsZenBoostsBackend',
        'headers': ['mozilla/nsZenBoostsBackend.h'],
        'processes': ProcessSelector.CONTENT_PROCESS_ONLY,
    },
]
