/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

%{C++
#include "nsColor.h"
%}

native nscolor(nscolor);

/**
 * @brief Interface for Zen boosts backend.
 */
[scriptable, uuid(7d46aa4e-7486-4f77-ab47-81125f1a5723)]
interface nsIZenBoostsBackend : nsISupports {
  /**
   * @brief Register a new Zen boost for a given domain.
   * @param aDomain The domain to register the boost for.
   * @param aAccentColor The accent color to use for the boost.
   */
  void RegisterZenBoost(in AString aDomain,
                        in Array<uint8_t> aAccentColor);

  /**
   * @brief Unregister a Zen boost for a given domain.
   * @param aDomain The domain to unregister the boost for.
   */
  void UnregisterZenBoost(in AString aDomain);
};
