/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

/**
 * @brief Interface for Zen boosts backend.
 */
[scriptable, uuid(7d46aa4e-7486-4f77-ab47-81125f1a5723)]
interface nsIZenBoostsBackend : nsISupports {
  %{C++
    /*
     * @brief Called when the presshell is entered. See nsDisplayListBuilder::EnterPresShell
     * for context.
     */
    auto onPressShellEntered(nsPresContext* aPresContext) -> void;

    /*
     * @brief Called when the presshell is exited.
     */
    auto onPressShellLeave(nsPresContext* aPresContext) -> void;

    /*
     * Recomputes the data dependent on the browsing context, like zoom and text
     * zoom. We use it to store Zen boosts related data too.
     */
    void RecomputeBrowsingContextDependentData(nsPresContext* aPresContext,
                                              mozilla::dom::BrowsingContext* aBrowsingContext);
  %}
};
