---
# Keep up to date with workflows/issue-create.yml !!!

policy:
  - section:
      - id: [severity]
        label:
          - name: 'kind: low severity'
            keys: ['Low']
          - name: 'kind: medium severity'
            keys: ['Medium']
          - name: 'kind: high severity'
            keys: ['High']
          - name: 'kind: critical severity'
            keys: ['Critical']
          - name: 'kind: enhancement'
            keys: ['Enhancement']

