
#ifndef ZEN_TOOLKIT_PROFILE_OVERRIDE
#define ZEN_TOOLKIT_PROFILE_OVERRIDE "Default Profile"
#endif

#ifndef ZEN_DO_NOT_OVERRIDE_DEFAULT_PROFILE_NAME
#undef DEFAULT_NAME
#define DEFAULT_NAME ZEN_TOOLKIT_PROFILE_OVERRIDE
#endif
