blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/ali-ezz/nevai-browser-desktop/discussions
    about: Please use GitHub discussions for Nevai Browser Desktop feature requests.
