name: Feature Request
description: File a feature request
labels: 
  - "kind: enhancement"
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like to see?
      description: Please describe the feature you would like to see.
      placeholder: I would like to see…
    validations:
      required: true
  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: Add any additional details about the feature request here.
