# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{03d900f7-639f-4c81-b029-2883dd893ccb}',
        'interfaces': ['nsIZenMouseTracker'],
        'contract_ids': ['@mozilla.org/zen/mouse-tracker;1'],
        'type': 'zen::ZenMouseTracker',
        'headers': ['mozilla/ZenMouseTracker.h'],
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
