name: Code Linter

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - dev

jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup autopep8
        run: sudo apt install python3-autopep8

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint
