name: Pull request test
permissions:
  contents: read

on:
  pull_request:
    branches:
      - dev

jobs:
  pr-test:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version-file: '.nvmrc'

      - name: Install Surfer
        run: npm i -g @zen-browser/surfer

      - name: Install dependencies
        run: npm install

      - name: Download Firefox and dependencies
        run: surfer download

      - name: Import patches
        run: surfer i
