name: Pull request test

on:
  pull_request:
    branches:
      - dev

jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Surfer
        run: pnpm i -g @zen-browser/surfer

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download Firefox and dependencies
        run: surfer download

      - name: Import patches
        run: surfer i
